Upgrade to Rails 5
alphagov/multipage-frontend pull request #45
Opened 2016-10-31 14:59 UTC by danielroseman

Mainly configuration changes and fixes for deprecations.

2016-11-17 09:37 UTC, cbaines commented on config/initializers/application_controller_renderer.rb
> +# )
I'll have a look at what this file is for in a bit, but it might be worth deleting it if it is unnecessary?

2016-11-17 09:48 UTC, kevindew approved these changes
Looks cool to me 👍

2016-11-17 09:57 UTC, boffbowsh requested changes
Maybe one change?

2016-11-17 09:57 UTC, boffbowsh commented on config/cable.yml
> +development:
I'd hope this isn't needed if Cable isn't required?

2016-11-17 09:57 UTC, boffbowsh commented on config/environments/development.rb
> +  if Rails.root.join('tmp/caching-dev.txt').exist?
Wow this is horrible. http://blog.bigbinary.com/2016/01/25/caching-in-development-environment-in-rails5.html

2016-11-17 09:57 UTC, boffbowsh commented on app/controllers/multipage_controller.rb
> +  rescue_from GdsApi::HTTPNotFound, with: :error_404
Nice.

2016-11-17 13:20 UTC, cbaines requested changes
Question regarding Airbreak configuration.

2016-11-17 13:23 UTC, cbaines requested changes
Comment on Airbreak configuration.

2016-11-17 13:23 UTC, cbaines commented on config/initializers/airbrake.rb
> +    config.host = errbit_uri
I think this might need to be a hostname (e.g. `errbit.#{ENV['GOVUK_APP_DOMAIN']}`) and not a URL as returned by Plek.

2016-11-17 13:43 UTC, cbaines commented on config/initializers/airbrake.rb
> +    config.host = errbit_uri
Just found this page, and it shows in examples that the host doesn't have to be a hostname, so maybe this is not an issue https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#port .

2016-11-18 09:28 UTC, danielroseman commented on config/initializers/airbrake.rb
> +    config.host = errbit_uri
This is the same code that we've used for all the various Rails 5 upgrades, eg https://github.com/alphagov/publishing-api/blob/master/config/initializers/airbrake.rb, so I'm confident it works.

2016-11-18 09:29 UTC, danielroseman commented on config/initializers/application_controller_renderer.rb
> +# )
We've tended to keep unused configuration files around, to reduce noise when upgrading.

2016-11-18 09:31 UTC, boffbowsh approved these changes

2016-11-18 09:31 UTC, cbaines commented on config/initializers/airbrake.rb
> +    config.host = errbit_uri
Ok. You might want to just use Plek.find, unless the String -> URI -> String conversion has some function?

2016-11-18 09:36 UTC, danielroseman commented on config/initializers/airbrake.rb
> +    config.host = errbit_uri
Yeah, that is what we are using here; I'd misunderstood the Plek interface when I did the others, I'll simplify them at some point.

2016-11-18 15:12 UTC, merged